apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "example.labels" . | nindent 4 }}
  name: {{ include "example.name" . }}
  namespace: {{ include "example.name" . }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "example.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
